# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca gem bigdecimal`.


# source://bigdecimal//lib/bigdecimal.rb#13
class BigDecimal < ::Numeric
  # call-seq:
  #    self ** other -> bigdecimal
  #
  #  Returns the \BigDecimal value of +self+ raised to power +other+:
  #
  #    b = BigDecimal('3.14')
  #    b ** 2              # => 0.98596e1
  #    b ** 2.0            # => 0.98596e1
  #    b ** Rational(2, 1) # => 0.98596e1
  #
  #  Related: BigDecimal#power.
  #
  # source://bigdecimal//lib/bigdecimal.rb#127
  def **(y); end

  # call-seq:
  #   power(n)
  #   power(n, prec)
  #
  # Returns the value raised to the power of n.
  #
  # Also available as the operator **.
  #
  # source://bigdecimal//lib/bigdecimal.rb#147
  def power(y, prec = T.unsafe(nil)); end

  # Returns the square root of the value.
  #
  # Result has at least prec significant digits.
  #
  # @raise [FloatDomainError]
  #
  # source://bigdecimal//lib/bigdecimal.rb#262
  def sqrt(prec); end
end

# source://bigdecimal//lib/bigdecimal.rb#14
module BigDecimal::Internal
  class << self
    # Coerce x to BigDecimal with the specified precision.
    # TODO: some methods (example: BigMath.exp) require more precision than specified to coerce.
    #
    # @raise [ArgumentError]
    #
    # source://bigdecimal//lib/bigdecimal.rb#21
    def coerce_to_bigdecimal(x, prec, method_name); end

    # source://bigdecimal//lib/bigdecimal.rb#33
    def coerce_validate_prec(prec, method_name, accept_zero: T.unsafe(nil)); end

    # Calculates Math.log(x.to_f) considering large or small exponent
    #
    # source://bigdecimal//lib/bigdecimal.rb#87
    def float_log(x); end

    # source://bigdecimal//lib/bigdecimal.rb#53
    def infinity_computation_result; end

    # source://bigdecimal//lib/bigdecimal.rb#67
    def nan_computation_result; end

    # Iteration for Newton's method with increasing precision
    #
    # source://bigdecimal//lib/bigdecimal.rb#75
    def newton_loop(prec, initial_precision: T.unsafe(nil), safe_margin: T.unsafe(nil)); end

    # Calculating Taylor series sum using binary splitting method
    # Calculates f(x) = (x/d0)*(1+(x/d1)*(1+(x/d2)*(1+(x/d3)*(1+...))))
    # x.n_significant_digits or ds.size must be small to be performant.
    #
    # source://bigdecimal//lib/bigdecimal.rb#94
    def taylor_sum_binary_splitting(x, ds, prec); end

    # source://bigdecimal//lib/bigdecimal.rb#60
    def underflow_computation_result; end
  end
end

# Default extra precision for intermediate calculations
# This value is currently the same as BigDecimal.double_fig, but defined separately for future changes.
#
# source://bigdecimal//lib/bigdecimal.rb#17
BigDecimal::Internal::EXTRA_PREC = T.let(T.unsafe(nil), Integer)

BigDecimal::VERSION = T.let(T.unsafe(nil), String)

# Core BigMath methods for BigDecimal (log, exp) are defined here.
# Other methods (sin, cos, atan) are defined in 'bigdecimal/math.rb'.
#
# source://bigdecimal//lib/bigdecimal.rb#288
module BigMath
  private

  # source://bigdecimal//lib/bigdecimal.rb#336
  def _exp_binary_splitting(x, prec); end

  # call-seq:
  #   BigMath.exp(decimal, numeric)    -> BigDecimal
  #
  # Computes the value of e (the base of natural logarithms) raised to the
  # power of +decimal+, to the specified number of digits of precision.
  #
  # If +decimal+ is infinity, returns Infinity.
  #
  # If +decimal+ is NaN, returns NaN.
  #
  # source://bigdecimal//lib/bigdecimal.rb#356
  def exp(x, prec); end

  # call-seq:
  #   BigMath.log(decimal, numeric)    -> BigDecimal
  #
  # Computes the natural logarithm of +decimal+ to the specified number of
  # digits of precision, +numeric+.
  #
  # If +decimal+ is zero or negative, raises Math::DomainError.
  #
  # If +decimal+ is positive infinity, returns Infinity.
  #
  # If +decimal+ is NaN, returns NaN.
  #
  # source://bigdecimal//lib/bigdecimal.rb#303
  def log(x, prec); end

  class << self
    # call-seq:
    #   BigMath.exp(decimal, numeric)    -> BigDecimal
    #
    # Computes the value of e (the base of natural logarithms) raised to the
    # power of +decimal+, to the specified number of digits of precision.
    #
    # If +decimal+ is infinity, returns Infinity.
    #
    # If +decimal+ is NaN, returns NaN.
    #
    # source://bigdecimal//lib/bigdecimal.rb#356
    def exp(x, prec); end

    # call-seq:
    #   BigMath.log(decimal, numeric)    -> BigDecimal
    #
    # Computes the natural logarithm of +decimal+ to the specified number of
    # digits of precision, +numeric+.
    #
    # If +decimal+ is zero or negative, raises Math::DomainError.
    #
    # If +decimal+ is positive infinity, returns Infinity.
    #
    # If +decimal+ is NaN, returns NaN.
    #
    # @raise [Math::DomainError]
    #
    # source://bigdecimal//lib/bigdecimal.rb#303
    def log(x, prec); end

    private

    # source://bigdecimal//lib/bigdecimal.rb#336
    def _exp_binary_splitting(x, prec); end
  end
end
