# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `filelock` gem.
# Please instead update this file by running `bin/tapioca gem filelock`.

# source://filelock//lib/filelock/version.rb#1
module Filelock; end

# source://filelock//lib/filelock/exec_timeout.rb#2
class Filelock::ExecTimeout < ::Timeout::Error
  # source://filelock//lib/filelock/exec_timeout.rb#3
  def message; end
end

# source://filelock//lib/filelock/version.rb#2
Filelock::VERSION = T.let(T.unsafe(nil), String)

# source://filelock//lib/filelock/wait_timeout.rb#2
class Filelock::WaitTimeout < ::Timeout::Error
  # source://filelock//lib/filelock/wait_timeout.rb#3
  def message; end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # source://filelock//lib/filelock.rb#16
  def Filelock(lockname, options = T.unsafe(nil), &block); end
end
