# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nori` gem.
# Please instead update this file by running `bin/tapioca gem nori`.


class Hash
  include ::Enumerable
  include ::Nori::CoreExt::Hash
end

# pkg:gem/nori#lib/nori/version.rb:1
class Nori
  # pkg:gem/nori#lib/nori.rb:16
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/nori#lib/nori.rb:36
  def find(hash, *path); end

  # pkg:gem/nori#lib/nori.rb:46
  def parse(xml); end

  private

  # Expects a +block+ which receives a tag to convert.
  # Accepts +nil+ for a reset to the default behavior of not converting tags.
  #
  # pkg:gem/nori#lib/nori.rb:85
  def convert_tags_to(reset = T.unsafe(nil), &block); end

  # pkg:gem/nori#lib/nori.rb:98
  def find_value(hash, key); end

  # pkg:gem/nori#lib/nori.rb:78
  def load_parser(parser); end

  # pkg:gem/nori#lib/nori.rb:107
  def scrub_xml(string); end

  # The defaults implied by the +:standards+ profile.
  #
  # The profile groups the spec-correct behaviors under a single opt-in.
  # It turns on the XML string-value model for empty elements
  # (+:consistent_empty_tags+ with an empty-string +:empty_tag_value+),
  # turns off +:advanced_typecasting+ (schema-less values are text, their
  # types are the business of a schema-aware layer) and, in the parsers,
  # honors xml:space. These are defaults, so an explicit option passed by
  # the caller still wins. When the profile is off the hash is empty and
  # parsing is unchanged.
  #
  # @param options [Hash] the options passed to {#initialize}
  # @return [Hash] the implied defaults, or +{}+ when the profile is off
  #
  # pkg:gem/nori#lib/nori.rb:69
  def standards_defaults(options); end

  # pkg:gem/nori#lib/nori.rb:89
  def validate_options!(available_options, options); end

  class << self
    # pkg:gem/nori#lib/nori.rb:7
    def hash_key(name, options = T.unsafe(nil)); end
  end
end

# pkg:gem/nori#lib/nori/core_ext/hash.rb:4
module Nori::CoreExt; end

# pkg:gem/nori#lib/nori/core_ext/hash.rb:5
module Nori::CoreExt::Hash
  # @param key<Object> The key for the param.
  # @param value<Object> The value for the param.
  #
  # @return <String> This key value pair as a param
  #
  # @example normalize_param(:name, "Bob Jones") #=> "name=Bob%20Jones"
  #
  # pkg:gem/nori#lib/nori/core_ext/hash.rb:13
  def normalize_param(key, value); end

  # @return <String> The hash as attributes for an XML tag.
  #
  # @example
  #   { :one => 1, "two"=>"TWO" }.to_xml_attributes
  #     #=> 'one="1" two="TWO"'
  #
  # pkg:gem/nori#lib/nori/core_ext/hash.rb:28
  def to_xml_attributes; end

  private

  # pkg:gem/nori#lib/nori/core_ext/hash.rb:52
  def encode_simple_value(value); end

  # pkg:gem/nori#lib/nori/core_ext/hash.rb:40
  def normalize_array_params(key, array); end

  # pkg:gem/nori#lib/nori/core_ext/hash.rb:46
  def normalize_hash_params(key, hash); end

  # pkg:gem/nori#lib/nori/core_ext/hash.rb:36
  def normalize_simple_type_params(key, value); end
end

# pkg:gem/nori#lib/nori.rb:14
Nori::PARSERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/nori#lib/nori/string_io_file.rb:4
class Nori::StringIOFile < ::StringIO
  # pkg:gem/nori#lib/nori/string_io_file.rb:6
  def content_type; end

  # pkg:gem/nori#lib/nori/string_io_file.rb:6
  def content_type=(_arg0); end

  # pkg:gem/nori#lib/nori/string_io_file.rb:6
  def original_filename; end

  # pkg:gem/nori#lib/nori/string_io_file.rb:6
  def original_filename=(_arg0); end
end

# pkg:gem/nori#lib/nori/string_utils.rb:2
module Nori::StringUtils
  class << self
    # Converts a string to snake case.
    #
    # @param inputstring [String] The string to be converted to snake case.
    # @return [String] A copy of the input string converted to snake case.
    #
    # pkg:gem/nori#lib/nori/string_utils.rb:7
    def snakecase(inputstring); end
  end
end

# pkg:gem/nori#lib/nori/string_with_attributes.rb:2
class Nori::StringWithAttributes < ::String
  # pkg:gem/nori#lib/nori/string_with_attributes.rb:4
  def attributes; end

  # pkg:gem/nori#lib/nori/string_with_attributes.rb:4
  def attributes=(_arg0); end
end

# pkg:gem/nori#lib/nori/version.rb:2
Nori::VERSION = T.let(T.unsafe(nil), String)

# This is a slighly modified version of the XMLUtilityNode from
# http://merb.devjavu.com/projects/merb/ticket/95 (has.sox@gmail.com)
#
# John Nunemaker:
# It's mainly just adding vowels, as I ht cd wth n vwls :)
# This represents the hard part of the work, all I did was change the
# underlying parser.
#
# pkg:gem/nori#lib/nori/xml_utility_node.rb:18
class Nori::XMLUtilityNode
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:86
  def initialize(options, name, attributes = T.unsafe(nil)); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:124
  def add_node(node); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:180
  def advanced_typecasting(value); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def attributes; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def attributes=(_arg0); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def children; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def children=(_arg0); end

  # Get the inner_html of the REXML node.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:203
  def inner_html; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def name; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def name=(_arg0); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:119
  def prefixed_attribute_name(attribute); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:112
  def prefixed_attributes; end

  # Converts the node into a hash with the node name as its single key.
  #
  # The value depends on the shape of the node. A node typed as "file"
  # becomes a {StringIOFile}, unless the +:serializable+ profile is enabled.
  # That profile returns plain data only, so a file node folds into text and
  # attributes like any other node and the base64 content is left undecoded.
  # A node with text content becomes a typecast scalar. Every other node
  # folds its children into an array or a hash. Under the +:standards+
  # profile no bare type attribute is honored ({#bare_type}), so file
  # decoding, array folding and typecasting never happen there.
  #
  # @return [Hash{String => Object}] the node name mapped to its value
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:141
  def to_hash; end

  # Converts the node into a readable HTML node.
  #
  # @return <String> The HTML node in text form.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:210
  def to_html; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:214
  def to_s; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def type; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:110
  def type=(_arg0); end

  # Typecasts a value based upon its type. For instance, if
  # +node+ has #type == "integer",
  # {{[node.typecast_value("12") #=> 12]}}
  #
  # @param value<String> The value that is being typecast.
  #
  # @details [:type options]
  #   "integer"::
  #     converts +value+ to an integer with #to_i
  #   "boolean"::
  #     checks whether +value+, after removing spaces, is the literal
  #     "true"
  #   "datetime"::
  #     Parses +value+ using Time.parse, and returns a UTC Time
  #   "date"::
  #     Parses +value+ using Date.parse
  #
  # @return <Integer, TrueClass, FalseClass, Time, Date, Object>
  #   The result of typecasting +value+.
  #
  # @note
  #   If +self+ does not have a "type" key, or if it's not one of the
  #   options specified above, the raw +value+ will be returned.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:174
  def typecast_value(value); end

  # Take keys of the form foo-bar and convert them to foo_bar
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:195
  def undasherize_keys(params); end

  private

  # Collects the values of all child nodes for a node typed as "array".
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:280
  def array_value(groups); end

  # The value of the bare (un-namespaced) type attribute, or nil under
  # the +:standards+ profile. A recognized type is consumed from the
  # attributes because typecasting replaces it with the value it
  # describes. An unrecognized type stays visible as an ordinary
  # attribute. The bare attribute is a Rails +Hash.from_xml+ convention
  # rather than XML, so the +:standards+ profile never reads it and the
  # attribute passes through as ordinary data.
  #
  # @param attributes [Hash{String => String}] the element's attributes
  # @return [String, nil] the type name, or nil when there is none to honor
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:228
  def bare_type(attributes); end

  # Resolves an element without children and without text when the
  # :consistent_empty_tags option is set. The element becomes the
  # :empty_tag_value option no matter which attributes it carries.
  # A string value keeps the attributes accessible on the value.
  # An explicit xsi:nil="true" wins over the option and becomes nil.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:314
  def consistent_empty_value; end

  # Decodes the base64 content of a node typed as "file" into a
  # {StringIOFile} carrying the filename and content type attributes.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:250
  def file_value; end

  # Groups the child nodes by their name so repeating siblings can be
  # folded into arrays.
  #
  # @return [Hash{String => Array<XMLUtilityNode>}]
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:275
  def group_children; end

  # Folds the child nodes and the prefixed attributes into a hash.
  # An empty result becomes the :empty_tag_value option.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:294
  def hash_value(groups); end

  # The attribute forms that declare an element nil. The prefixed form
  # is the XML Schema Instance convention (xsi:nil). The bare +nil+ form
  # is a Rails +Hash.from_xml+ convention, so the +:standards+ profile
  # only accepts the prefixed form.
  #
  # @return [Regexp] the pattern, with the prefix in capture group 2
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:244
  def nil_attribute_pattern; end

  # The +:serializable+ representation of a +value+ and the node's
  # attributes. A node with attributes maps to the XML JSON convention
  # (+{"#text" => value}+ merged with the "@"-prefixed attributes) and a
  # node without attributes maps to the plain value. This holds for
  # typecast non-String values too, so attributes are never silently
  # dropped under the profile. The +#text+ key and the attribute keys go
  # through the same tag conversion as every other key
  # ({#prefixed_attribute_name}), so a +:convert_tags_to+ formula sees
  # each key Nori emits.
  #
  # @param value [Object] the typecast text content of the node
  # @return [Hash{String => Object}, Object] the hash shape when the node
  #   has attributes, otherwise the plain +value+
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:353
  def serializable_value(value); end

  # Combines a string +value+ with the node's attributes in the shape the
  # active output profile calls for.
  #
  # By default the value is a {StringWithAttributes}: a String carrying the
  # node's attributes on {StringWithAttributes#attributes}. Under the
  # +:serializable+ profile the value becomes plain, directly-serializable
  # data instead, so no custom String subclass is returned.
  #
  # @param value [String] the typecast text content of the node
  # @return [StringWithAttributes, Hash{String => String}, String] the value
  #   in the configured representation
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:332
  def string_with_attributes(value); end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:364
  def strip_namespace(string); end

  # Typecasts the text content of the node. String results are wrapped
  # so the node's attributes stay accessible on the value. Typecast
  # non-String results can only carry the attributes under the
  # +:serializable+ profile, where every value with attributes takes the
  # hash shape. Without the profile they are returned bare and the
  # attributes are dropped, because a {StringWithAttributes} cannot wrap
  # them.
  #
  # pkg:gem/nori#lib/nori/xml_utility_node.rb:264
  def text_value; end

  # pkg:gem/nori#lib/nori/xml_utility_node.rb:358
  def try_to_convert(value, &block); end

  class << self
    # pkg:gem/nori#lib/nori/xml_utility_node.rb:64
    def available_typecasts; end

    # pkg:gem/nori#lib/nori/xml_utility_node.rb:68
    def available_typecasts=(obj); end

    # pkg:gem/nori#lib/nori/xml_utility_node.rb:56
    def typecasts; end

    # pkg:gem/nori#lib/nori/xml_utility_node.rb:60
    def typecasts=(obj); end
  end
end

# Simple xs:date Regexp.
# Valid xs:date formats
# 2004-04-12           April 12, 2004
# -0045-01-01          January 1, 45 BC
# 12004-04-12          April 12, 12004
# 2004-04-12-05:00     April 12, 2004, US Eastern Standard Time, which is 5 hours behind Coordinated Universal Time (UTC)
# 2004-04-12+02:00     April 12, 2004, Central European Summer Time, which is 2 hours ahead of Coordinated Universal Time (UTC)
# 2004-04-12Z          April 12, 2004, Coordinated Universal Time (UTC)
#
# pkg:gem/nori#lib/nori/xml_utility_node.rb:42
Nori::XMLUtilityNode::XS_DATE = T.let(T.unsafe(nil), Regexp)

# Simple xs:dateTime Regexp.
# Valid xs:dateTime formats
# 2004-04-12T13:20:00           1:20 pm on April 12, 2004
# 2004-04-12T13:20:15.5         1:20 pm and 15.5 seconds on April 12, 2004
# 2004-04-12T13:20:00-05:00     1:20 pm on April 12, 2004, US Eastern Standard Time
# 2004-04-12T13:20:00+02:00     1:20 pm on April 12, 2004, Central European Summer Time
# 2004-04-12T13:20:15.5-05:00   1:20 pm and 15.5 seconds on April 12, 2004, US Eastern Standard Time
# 2004-04-12T13:20:00Z          1:20 pm on April 12, 2004, Coordinated Universal Time (UTC)
# 2004-04-12T13:20:15.5Z        1:20 pm and 15.5 seconds on April 12, 2004, Coordinated Universal Time (UTC)
#
# pkg:gem/nori#lib/nori/xml_utility_node.rb:54
Nori::XMLUtilityNode::XS_DATE_TIME = T.let(T.unsafe(nil), Regexp)

# Simple xs:time Regexp.
# Valid xs:time formats
# 13:20:00          1:20 PM
# 13:20:30.5555     1:20 PM and 30.5555 seconds
# 13:20:00-05:00    1:20 PM, US Eastern Standard Time
# 13:20:00+02:00    1:20 PM, Central European Standard Time
# 13:20:00Z         1:20 PM, Coordinated Universal Time (UTC)
# 13:20:30.5555Z    1:20 PM and 30.5555 seconds, Coordinated Universal Time (UTC)
# 00:00:00          midnight
# 24:00:00          midnight
#
# pkg:gem/nori#lib/nori/xml_utility_node.rb:31
Nori::XMLUtilityNode::XS_TIME = T.let(T.unsafe(nil), Regexp)
