# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rtoolsHCK` gem.
# Please instead update this file by running `bin/tapioca gem rtoolsHCK`.


# ether class
#
# pkg:gem/rtoolsHCK#lib/ether.rb:10
class Ether
  # pkg:gem/rtoolsHCK#lib/ether.rb:11
  def initialize(init_opts); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:142
  def close; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:154
  def cmd(cmd, timeout = T.unsafe(nil)); end

  private

  # pkg:gem/rtoolsHCK#lib/ether.rb:95
  def connect; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:119
  def fetch(length); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:104
  def fetch_output_with_timeout(timeout); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:173
  def flush; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:26
  def get_exception_stack(exception); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:76
  def load_ether; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:48
  def load_instance_variables(init_opts); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:70
  def load_server; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:31
  def log_exception(exception, level); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:43
  def logger(level, progname = T.unsafe(nil), &_arg2); end

  # pkg:gem/rtoolsHCK#lib/ether.rb:58
  def server_init_opts; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:130
  def unload_server; end

  # pkg:gem/rtoolsHCK#lib/ether.rb:83
  def wait_for_client_acceptance; end
end

# ether buffer size
#
# pkg:gem/rtoolsHCK#lib/ether.rb:117
Ether::ETHER_BUFFER_SIZE = T.let(T.unsafe(nil), Integer)

# ether exit timeout
#
# pkg:gem/rtoolsHCK#lib/ether.rb:138
Ether::ETHER_EXIT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# A custom Ether error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:28
class EtherError < ::RToolsHCKConnectionError; end

# == Description
#
# A ruby class the resembles tool set for HCK\HLK with various purposes which
# covers several actions as explained in the list if actions below.
#
# == Actions list
#
# +list_pools+::                 Lists the pools info.
#
# +create_pool+::                Creates a pool.
#
# +delete_pool+::                Deletes a pool.
#
# +move_machine+::               Moves a machine from one pool to another.
#
# +set_machine_state+::          Sets the state of a machine to Ready or
#                                NotReady.
#
# +delete_machine+::             Deletes a machine
#
# +list_machine_targets+::       Lists the target devices of a machine that are
#                                available to be tested.
#
# +list_projects+::              Lists the projects info.
#
# +create_project+::             Creates a project.
#
# +delete_project+::             Deletes a project.
#
# +create_project_target+::      Creates a project's target.
#
# +delete_project_target+::      Deletes a project's target.
#
# +list_tests+::                 Lists a project target's tests.
#
# +get_test_info+::              Gets a project target's test info.
#
# +queue_test+::                 Queue's a test, use get_test_results to get the
#                                results.
#
# +update_filters+::             Updates the HCK\HLK controller's filters.
#
# +apply_project_filters+::      Applies the filters on a project's test
#                                results.
#
# +apply_test_result_filters+::  Applies the filters on a test result.
#
# +list_test_results+::          Lists a test results info.
#
# +zip_test_result_logs+::       Zipps a test result's log and fetches the zip.
#
# +create_project_package+::     Creates a project's package.
# rtoolsHCK version extend to class
#
# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:67
class RToolsHCK
  # == Description
  #
  # Initializes new object of type RToolsHCK to be used by establishing a
  # Telnet and a Tftp connection with the guest machine.
  #
  # == Params:
  #
  # +init_opts+::    Hash that has various initialize options to configure upon
  #                  initializing a RtoolsHCK object:
  #   :addr          - Controller/Studio machine's IP address
  #                    (default: 192.168.100.1)
  #                    (default is based on HLK-Setup-Script settings)
  #   :port          - The port to be used for the WinRM connection
  #                    (default: 5985)
  #   :ether_port    - The port to be used for the toolsHCK Ether connection
  #                    (default: 4000)
  #   :user          - The user name to use in order to connect via WinRM to the
  #                    guest
  #                    (default: Administrator)
  #   :pass          - The password of the user name specified
  #                    (default: PASSWORD)
  #   :clients_addrs - The clients WinRM connection ip and port (default: 5985) as a hash
  #                    (example: { 'Client' => { addr: '192.168.0.18', port: 4001 }, ... })
  #                    (default: { 'CL1' => { addr: '192.168.100.2' }, 'CL2' => { addr: '192.168.100.3' } })
  #                    (default is based on HLK-Setup-Script settings)
  #   :json          - JSON format the output of the action methods
  #                    (default: true)
  #   :timeout       - The action's timeout in seconds
  #                    (default: 60)
  #   :log_to_stdout - Log to STDOUT switch
  #                    (default: false)
  #   :logger        - The ruby logger object for logging
  #                    (default: disabled)
  #   :outp_dir      - The path of the directory to fetch the output files to on
  #                    the local machine
  #                    (default: disabled)
  #   :r_script_file - The toolsHCK.ps1 file path on remote machine
  #                    (default: C:\\toolsHCK.ps1)
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:146
  def initialize(init_opts); end

  # == Description
  #
  # Applies the filters on a project's test results.
  #
  # == Params:
  #
  # +project+::      The name of the project
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:865
  def apply_project_filters(project); end

  # == Description
  #
  # Applies the filters on a test result.
  #
  # == Params:
  #
  # +result+::       The index of the test result, use list_test_results action
  #                  to get it
  # +test+::         The id of the test, use list_tests action to get it
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:888
  def apply_test_result_filters(result, test, target, project, machine, pool); end

  # == Description
  #
  # Closes the instance.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1563
  def close; end

  # == Description
  #
  # Closes the instance and shuts down the studio.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1548
  def close_and_shutdown; end

  # == Description
  #
  # Boolean method to the instance being closed.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1576
  def closed?; end

  # == Description
  #
  # Checks if connection is still alive.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1531
  def connection_check; end

  # == Description
  #
  # Creates a pool.
  #
  # == Params:
  #
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:471
  def create_pool(pool); end

  # == Description
  #
  # Creates a project.
  #
  # == Params:
  #
  # +project+::      The name of the project
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:588
  def create_project(project); end

  # == Description
  #
  # Creates a project's package and saves it to a file at <package> if used,
  # if not to %TEMP%\prometheus_packages\..., also fetches the package file to
  # the local machine if outp_dir param was used on initialization.
  #
  # == Params:
  #
  # +project+::      The name of the project
  # +playlist+::     Provide a playlist file path to apply, (can be nil)
  # +handler+::      The progress info handler, (can be nil), usage example:
  #                    handler = proc { |progress_package|
  #                      puts progress_package['stepscount']
  #                    }
  #                  progress_package is in JSON format and it has:
  #                  1. 'stepscount': a numeric progression steps count
  #                  1. 'steps': an array of 'stepscount' JSON entries that
  #                     each entry represents a single progression step's
  #                     progress info, each entry's content:
  #                     i. 'current': current progress counter value
  #                     i. 'maximum': maximum progress counter value
  #                     i. 'message': progress info message
  #
  # +driver_path+::  Provide a driver path to include, (can be nil)
  # +supplemental_path+:: Provide a supplemental path to include, (can be nil)
  # +remove_driver_signatures+:: If true, remove driver signatures before
  #                              packaging (default: false)
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1095
  def create_project_package(project, playlist = T.unsafe(nil), handler = T.unsafe(nil), driver_path = T.unsafe(nil), supplemental_path = T.unsafe(nil), remove_driver_signatures: T.unsafe(nil)); end

  # == Description
  #
  # Creates a project's target.
  #
  # == Params:
  #
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:624
  def create_project_target(target, project, machine, pool); end

  # == Description
  #
  # Deletes a machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:542
  def delete_machine(machine, pool); end

  # == Description
  #
  # Delete the given path on the target machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +r_directory+::  The remote file/directory which should be deleted
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1297
  def delete_on_machine(machine, r_path); end

  # == Description
  #
  # Deletes a pool.
  #
  # == Params:
  #
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:487
  def delete_pool(pool); end

  # == Description
  #
  # Deletes a project.
  #
  # == Params:
  #
  # +project+::      The name of the project
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:604
  def delete_project(project); end

  # == Description
  #
  # Deletes a project's target.
  #
  # == Params:
  #
  # +target+::        The key of the target, use list_machine_targets to get it
  # +project+::       The name of the project
  # +machine+::       The name of the machine as registered with the HCK\HLK
  #                   controller
  # +pool+::          The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:647
  def delete_project_target(target, project, machine, pool); end

  # == Description
  #
  # Download file or directory from the machine to local directory.
  # BE CAREFUL! Download speed far less than upload one.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +r_directory+::  The remote file/directory which should be downloaded
  # +l_directory+::  The local file/directory path
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1265
  def download_from_machine(machine, r_path, l_path); end

  # == Description
  #
  # Checks to see if the given path exists on the target machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +r_directory+::  The remote file/directory which should be checked
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1281
  def exists_on_machine?(machine, r_path); end

  # == Description
  #
  # Gets a machine's ip address.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +ipv6+::         Get IPv6 address, :ipv6 to enable, disabled by default
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1124
  def get_machine_ip(machine, ipv6: T.unsafe(nil)); end

  # == Description
  #
  # Gets a machine's system information.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +output_format:: Specifies the format in which the output
  #                  is to be displayed.
  #                  Valid values: "TABLE", "LIST", "CSV".
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1145
  def get_machine_system_info(machine, output_format = T.unsafe(nil)); end

  # == Description
  #
  # Gets a project target's test info.
  #
  # == Params:
  #
  # +test+::         The id of the test, use list_tests action to get it
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:776
  def get_test_info(test, target, project, machine, pool); end

  # == Description
  #
  # Installs a driver package, (.inf file), on a machine.
  #
  # == Params:
  #
  # +machine+::             The name of the machine
  # +install_method+::      The method for driver installation
  # +l_directory+::         The local directory which has the driver package,
  #                         (.inf file)
  # +inf_file+::            The .inf file name
  #
  # == Optional params (symbols):
  #
  # +custom_cmd+::          The custom command for driver installation (optional)
  # +force_install_cert+::  Install certificate independently of driver installation
  #                         method (optional)
  # +sys_file+::            The .sys file name for export certificate (optional)
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1454
  def install_machine_driver_package(machine, install_method, l_directory, inf_file, options = T.unsafe(nil)); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:449
  def json; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:449
  def json=(_arg0); end

  # == Description
  #
  # Lists the target devices of a machine that are available to be tested.
  #
  # == Params:
  #
  # +machine+::      The name of the machine
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:559
  def list_machine_targets(machine, pool); end

  # == Description
  #
  # Lists the pools info.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:455
  def list_pools; end

  # == Description
  #
  # Lists the projects info.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:572
  def list_projects; end

  # == Description
  #
  # Lists a test's results info.
  #
  # == Params:
  #
  # +test_id+::      The id of the test, use list_tests action to get it
  #                  If id is nil, all tests results will be listed
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:918
  def list_test_results(test_id, target, project, machine, pool); end

  # == Description
  #
  # Lists a project target's tests.
  #
  # == Params:
  #
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  # +test_type+::    Assign to manual or auto, (can be nil)
  # +test_status+::  Assign to failed, inqueue, notrun, passed or running,
  #                  (can be nil)
  # +playlist+::     Provide a playlist file path to apply, (can be nil)
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:700
  def list_tests(target, project, machine, pool, test_type = T.unsafe(nil), test_status = T.unsafe(nil), playlist = T.unsafe(nil)); end

  # == Description
  #
  # Shuts down or restarts a machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +restart+::      Restarts the machine, :restart to enable, disabled by
  #                  default
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1180
  def machine_shutdown(machine, restart: T.unsafe(nil)); end

  # == Description
  #
  # Moves a machine from one pool to another.
  #
  # == Params:
  #
  # +machine+::      The name of the machine
  # +from+::         The name of the source pool
  # +to+::           The name of the destination pool
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:505
  def move_machine(machine, from, to); end

  # == Description
  #
  # Queues a test, use get_test_results action to get the results.
  # (if the test needs two machines to run use -sup flag)
  # (if the test needs the IPv6 address of the support machine use -IPv6 flag)
  #
  # == Params:
  #
  # +test+::         The id of the test, use list_tests action to get it
  # +target+::       The key of the target, use list_machine_targets to get it
  # +project+::      The name of the project
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +pool+::         The name of the pool
  # +sup+::          The name of the support machine as registered with the
  #                  HCK\HLK controller, (can be nil)
  # +parameters+::   Additional parameters in format '{ ParameterName1: Value1, ParameterName2: Value2 }', (can be nil)
  # +ipv6+::         The IPv6 address of the support machine, (can be nil)
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:806
  def queue_test(test, target, project, machine, pool, sup = T.unsafe(nil), parameters = T.unsafe(nil), ipv6 = T.unsafe(nil)); end

  # == Description
  #
  # Tries to regain the connection to the guest machine using the given
  # credentials and addresses on initialization.
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1477
  def reconnect; end

  # == Description
  #
  # Run command on a machine, (powershell).
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +cmd+::          The command to run as a string
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1199
  def run_on_machine(machine, cmd); end

  # == Description
  #
  # Run command on a studio, (powershell).
  #
  # == Params:
  #
  # +command+::          The command to run as a string
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1213
  def run_on_studio(command); end

  # == Description
  #
  # Sets the state of a machine to Ready or NotReady.
  #
  # == Params:
  #
  # +machine+::      The name of the machine
  # +pool+::         The name of the pool
  # +state+::        The state, Ready or NotReady
  # +timeout+::      The action's timeout in seconds, 60 by deafult
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:524
  def set_machine_state(machine, pool, state, timeout = T.unsafe(nil)); end

  # == Description
  #
  # Shuts down or restarts the studio, (you will need to reconnect after this).
  #
  # == Params:
  #
  # +restart+::      Restarts the machine, :restart to enable, disabled by
  #                  default
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1160
  def shutdown(restart: T.unsafe(nil)); end

  # == Description
  #
  # Starts HLK related services at the machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:240
  def start_client_services(machine); end

  # == Description
  #
  # Updates the HCK\HLK controller's filters by giving a local .sql filter file.
  #
  # == Params:
  #
  # +l_filters+::    The local filter .sql file path
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:849
  def update_filters(l_filter); end

  # == Description
  #
  # Upload directory to temp directory of the machine.
  #
  # == Params:
  #
  # +machine+::      The name of the machine as registered with the HCK\HLK
  #                  controller
  # +l_directory+::  The local file/directory which should be uploaded
  # +r_directory+::  The remote file/directory
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1232
  def upload_to_machine(machine, l_directory, r_directory = T.unsafe(nil)); end

  # == Description
  #
  # Upload file/directory to the studio machine.
  #
  # == Params:
  #
  # +l_path+::       The local file/directory path
  # +r_path+::       The remote destination path
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1247
  def upload_to_studio(l_path, r_path); end

  # == Description
  #
  # Zips a test result's logs to a zip file fetches it to the local machine if
  # logs_dir param was used on initialization.
  #
  # == Params:
  #
  # +result_index+::         If index_instance_id is false the index of the test result,
  #                          use list_test_results action to get it
  #                          If index_instance_id is true the instance id of the test result
  # +test+::                 The id of the test, use list_tests action to get it
  # +target+::               The key of the target, use list_machine_targets to get it
  # +project+::              The name of the project
  # +machine+::              The name of the machine as registered with the HCK\HLK
  #                          controller
  # +pool+::                 The name of the pool
  # +index_instance_id+::    If true, the result_index is treated as an instance id
  #
  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:953
  def zip_test_result_logs(result_index:, test:, target:, project:, machine:, pool:, index_instance_id: T.unsafe(nil)); end

  private

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:419
  def action_exception_handler(exception); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1514
  def check_connection; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:309
  def check_run_output(run_output, where, cmd); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1337
  def do_delete_on_machine(machine, r_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1318
  def do_download_from_machine(machine, r_path, l_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1329
  def do_exists_on_machine?(machine, r_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:248
  def do_initialize(init_opts); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1417
  def do_install_machine_driver_package(machine, install_method, l_directory, inf_file, options); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:674
  def do_list_tests(cmd_line, l_playlist); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:829
  def do_upload_and_update_filter(l_filter); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:661
  def do_upload_playlist_file(l_playlist); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1306
  def do_upload_to_machine(machine, l_directory, r_directory = T.unsafe(nil)); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1036
  def dummy_package_progress_info_handler; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1345
  def export_certificate_script(sys_path, cer_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:719
  def file_to_outp_dir(r_file_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1384
  def get_custom_command(r_directory, windows_path, custom_cmd); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:83
  def get_exception_stack(exception); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:383
  def guest_basename(path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:387
  def guest_dirname(path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:429
  def handle_action_exceptions(action, &block); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1054
  def handle_create_project_package(cmd_line, handler); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:76
  def handle_exceptions; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1008
  def handle_project_package(ret_str); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:976
  def handle_project_package_json(project_package); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:998
  def handle_project_package_normal(project_package, stream); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:393
  def handle_return(stream); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:752
  def handle_test_results(test_results, stream); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:727
  def handle_test_results_json(test_results); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:738
  def handle_test_results_normal(test_results, stream); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1400
  def install_certificate(machine, windows_path, sys_file = T.unsafe(nil)); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1356
  def install_certificate_script(cer_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1388
  def install_driver_command(r_directory, windows_path, install_method, custom_cmd = T.unsafe(nil)); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1377
  def install_driver_list(r_directory, windows_path); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:275
  def load_instance_variables(init_opts); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:263
  def load_outp_dir(outp_dir); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:365
  def load_toolshck; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:352
  def load_winrm_fs; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:300
  def load_winrm_ps; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:413
  def log_action_call(action, binding); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:88
  def log_exception(exception, level); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:100
  def logger(level, progname = T.unsafe(nil), &_arg2); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:326
  def machine_connection(machine); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:340
  def machine_run(machine, cmd); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1031
  def package_progress_info_factory(progress_steps); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1041
  def package_progression_first_step(cmd_line, handler); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1047
  def package_progression_last_step(current, handler); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1021
  def package_progression_loop(current, maximum, handler); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:402
  def parse_action_parameters(action, binding); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:988
  def parse_project_package_guest_path(stream); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1488
  def priv_close; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1363
  def replace_command(cmd, replacement_list); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:318
  def run(cmd); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:227
  def start_client_service(machine, service_name); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:209
  def start_studio_service(service_name); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:221
  def start_studio_services; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:369
  def toolshck_ether_init_opts; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1503
  def unload_ether; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1510
  def unload_toolshck; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1495
  def unload_winrm_ps; end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:194
  def validate_init_opts(init_opts); end

  # pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:288
  def winrm_options_factory(addr, port, user, pass); end
end

# Actions that can be performed in no_studio mode (client-only actions)
#
# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:161
RToolsHCK::CLIENT_ACTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:72
RToolsHCK::ETHER_DEFAULT_PORT = T.let(T.unsafe(nil), Integer)

# init_opts initialization defaults
#
# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:175
RToolsHCK::INIT_OPTS_DEFAULTS = T.let(T.unsafe(nil), Hash)

# Progression rate divider, used for the synchronization with the controller
#
# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:1064
RToolsHCK::PROGRESSION_RATE_DIVIDER = T.let(T.unsafe(nil), Integer)

# toolsHCK connection timeout in seconds
#
# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:363
RToolsHCK::TOOLSHCK_CONNECTION_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:71
RToolsHCK::WINRM_DEFAULT_PORT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:68
RToolsHCK::WINRM_OPERATION_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:69
RToolsHCK::WINRM_RECIEVE_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/rtoolsHCK#lib/rtoolsHCK.rb:70
RToolsHCK::WINRM_RETRY_INTERVAL = T.let(T.unsafe(nil), Integer)

# A custom RToolsHCK action error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:19
class RToolsHCKActionError < ::RToolsHCKError; end

# A custom RToolsHCK connection error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:16
class RToolsHCKConnectionError < ::RToolsHCKError; end

# A custom RToolsHCK error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:4
class RToolsHCKError < ::StandardError
  # Initialization of the custom exception
  #
  # pkg:gem/rtoolsHCK#lib/exceptions.rb:9
  def initialize(where); end

  # Custom addition to the exception backtrace, (better logging)
  #
  # pkg:gem/rtoolsHCK#lib/exceptions.rb:6
  def where; end
end

# server class
#
# pkg:gem/rtoolsHCK#lib/server.rb:8
class Server
  # pkg:gem/rtoolsHCK#lib/server.rb:9
  def initialize(init_opts); end

  # pkg:gem/rtoolsHCK#lib/server.rb:106
  def close; end

  # pkg:gem/rtoolsHCK#lib/server.rb:17
  def run_server; end

  private

  # pkg:gem/rtoolsHCK#lib/server.rb:44
  def check_script_file; end

  # pkg:gem/rtoolsHCK#lib/server.rb:54
  def deploy_script_file; end

  # pkg:gem/rtoolsHCK#lib/server.rb:100
  def guest_basename(path); end

  # pkg:gem/rtoolsHCK#lib/server.rb:36
  def load_instance_variables(init_opts); end

  # pkg:gem/rtoolsHCK#lib/server.rb:75
  def load_toolshck_server; end

  # pkg:gem/rtoolsHCK#lib/server.rb:31
  def logger(level, progname = T.unsafe(nil), &_arg2); end

  # pkg:gem/rtoolsHCK#lib/server.rb:94
  def process_script; end

  # pkg:gem/rtoolsHCK#lib/server.rb:62
  def start_server_with_log_fetcher; end
end

# A custom Server error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:25
class ServerError < ::RToolsHCKConnectionError; end

# A custom Winrm powershell run error exception
#
# pkg:gem/rtoolsHCK#lib/exceptions.rb:22
class WinrmPSRunError < ::RToolsHCKActionError; end
