# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `winrm` gem.
# Please instead update this file by running `bin/tapioca gem winrm`.


# Main WinRM module entry point
# Copyright 2010 Dan Wanek <dan.wanek@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Copyright 2014 Max Lincoln <max@devopsy.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Copyright 2016 Matt Wrock <matt@mattwrock.com>
# Copyright 2016 Shawn Neal <sneal@sneal.net>
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Copyright 2016 Matt Wrock <matt@mattwrock.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Copyright 2016 Shawn Neal <sneal@sneal.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# WinRM module
# Format an ISO8601 Duration
# Copyright 2010 Dan Wanek <dan.wanek@gmail.com>
# Copyright 2016 Shawn Neal <sneal@sneal.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pkg:gem/winrm#lib/winrm/compat_logger.rb:5
module WinRM
  class << self
    # Default log level used by WinRM loggers, controlled by the
    # WINRM_LOG environment variable. Falls back to :warn when unset
    # or invalid.
    # @return [Symbol] One of :debug, :info, :warn, :error or :fatal
    #
    # pkg:gem/winrm#lib/winrm.rb:29
    def default_log_level; end
  end
end

# Backwards-compatible default for `Connection#logger`.
#
# WinRM used to expose a `logging`-gem logger here; it now exposes a plain
# stdlib {Logger} instead. This subclass keeps the small `logging`-specific
# API callers actually used (`add_appenders`) working while emitting a
# deprecation warning, so existing code keeps running instead of breaking
# on upgrade. Everything else is exactly stdlib `Logger` behavior.
#
# pkg:gem/winrm#lib/winrm/compat_logger.rb:13
class WinRM::CompatLogger < ::Logger
  # Accepts `logging`-gem-style appenders for backwards compatibility.
  # Stdlib loggers write to their log device, so appenders have no
  # equivalent here and are ignored.
  #
  # pkg:gem/winrm#lib/winrm/compat_logger.rb:17
  def add_appenders(*_appenders); end

  private

  # pkg:gem/winrm#lib/winrm/compat_logger.rb:24
  def deprecate_appenders; end
end

# WinRM connection used to establish a session with the remote WinRM service.
#
# pkg:gem/winrm#lib/winrm/connection.rb:23
class WinRM::Connection
  # Creates a new WinRM connection
  # See the ConnectionOpts class for connection options.
  #
  # pkg:gem/winrm#lib/winrm/connection.rb:26
  def initialize(connection_opts); end

  # pkg:gem/winrm#lib/winrm/connection.rb:31
  def logger; end

  # pkg:gem/winrm#lib/winrm/connection.rb:31
  def logger=(_arg0); end

  # Executes a WQL query against the WinRM connection
  # @param wql [String] The wql query
  # @param namespace [String] namespace for query - default is root/cimv2/*
  # @return [Hash] Hash representation of wql query response (Hash is empty if a block is given)
  # @yeild [type, item] Yields the time name and item for every item
  #
  # pkg:gem/winrm#lib/winrm/connection.rb:56
  def run_wql(wql, namespace = T.unsafe(nil), &block); end

  # Creates a new shell on the remote Windows server associated with
  # this connection.
  # @param shell_type [Symbol] The shell type :cmd or :powershell
  # @param shell_opts [Hash] Options targeted for the created shell
  # @return [Shell] PowerShell or Cmd shell instance.
  #
  # pkg:gem/winrm#lib/winrm/connection.rb:38
  def shell(shell_type, shell_opts = T.unsafe(nil)); end

  private

  # pkg:gem/winrm#lib/winrm/connection.rb:63
  def configure_connection_opts(connection_opts); end

  # pkg:gem/winrm#lib/winrm/connection.rb:67
  def configure_logger; end

  # pkg:gem/winrm#lib/winrm/connection.rb:71
  def shell_factory; end

  # pkg:gem/winrm#lib/winrm/connection.rb:75
  def transport; end
end

# WinRM connection options, provides defaults and validation.
#
# pkg:gem/winrm#lib/winrm/connection_opts.rb:19
class WinRM::ConnectionOpts < ::Hash
  # pkg:gem/winrm#lib/winrm/connection_opts.rb:60
  def validate; end

  private

  # pkg:gem/winrm#lib/winrm/connection_opts.rb:85
  def validate_data_types; end

  # pkg:gem/winrm#lib/winrm/connection_opts.rb:93
  def validate_integer(key, min = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/connection_opts.rb:80
  def validate_kerberos_fields; end

  # pkg:gem/winrm#lib/winrm/connection_opts.rb:67
  def validate_required_fields; end

  class << self
    # pkg:gem/winrm#lib/winrm/connection_opts.rb:29
    def create_with_defaults(overrides); end

    private

    # pkg:gem/winrm#lib/winrm/connection_opts.rb:45
    def default; end

    # pkg:gem/winrm#lib/winrm/connection_opts.rb:38
    def ensure_receive_timeout_is_greater_than_operation_timeout(config); end
  end
end

# pkg:gem/winrm#lib/winrm/connection_opts.rb:23
WinRM::ConnectionOpts::DEFAULT_LOCALE = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:22
WinRM::ConnectionOpts::DEFAULT_MAX_ENV_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:20
WinRM::ConnectionOpts::DEFAULT_OPERATION_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:21
WinRM::ConnectionOpts::DEFAULT_RECEIVE_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:24
WinRM::ConnectionOpts::DEFAULT_RETRY_DELAY = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:25
WinRM::ConnectionOpts::DEFAULT_RETRY_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/connection_opts.rb:26
WinRM::ConnectionOpts::DEFAULT_USER_AGENT = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/http/transport.rb:19
module WinRM::HTTP; end

# Uses SSL to secure the transport
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:266
class WinRM::HTTP::BasicAuthSSL < ::WinRM::HTTP::HttpTransport
  # pkg:gem/winrm#lib/winrm/http/transport.rb:267
  def initialize(endpoint, user, pass, opts); end
end

# Uses Client Certificate to authenticate and SSL to secure the transport
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:279
class WinRM::HTTP::ClientCertAuthSSL < ::WinRM::HTTP::HttpTransport
  # pkg:gem/winrm#lib/winrm/http/transport.rb:280
  def initialize(endpoint, client_cert, client_key, key_pass, opts); end
end

# Uses Kerberos/GSSAPI to authenticate and encrypt messages
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:292
class WinRM::HTTP::HttpGSSAPI < ::WinRM::HTTP::HttpTransport
  # @param [String,URI] endpoint the WinRM webservice endpoint
  # @param [String] realm the Kerberos realm we are authenticating to
  # @param [String<optional>] service the service name, default is HTTP
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:296
  def initialize(endpoint, realm, opts, service = T.unsafe(nil)); end

  # Sends the SOAP payload to the WinRM service and returns the service's
  # SOAP response. If an error occurrs an appropriate error is raised.
  #
  # @param [String] The XML SOAP message
  # @returns [REXML::Document] The parsed response body
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:314
  def send_request(message); end

  private

  # pkg:gem/winrm#lib/winrm/http/transport.rb:354
  def init_krb; end

  # Sends the SOAP payload to the WinRM service and returns the service's
  # HTTP response.
  #
  # @param [String] The XML SOAP message
  # @returns [Object] The HTTP response object
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:334
  def send_kerberos_request(message); end

  # @return [String] the unencrypted response string
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:420
  def winrm_decrypt(str); end

  # @return [String] the encrypted request string
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:377
  def winrm_encrypt(str); end
end

# NTLM/Negotiate, secure, HTTP transport
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:149
class WinRM::HTTP::HttpNegotiate < ::WinRM::HTTP::HttpTransport
  # pkg:gem/winrm#lib/winrm/http/transport.rb:150
  def initialize(endpoint, user, pass, opts); end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:169
  def send_request(message); end

  private

  # pkg:gem/winrm#lib/winrm/http/transport.rb:251
  def channel_binding(response); end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:231
  def init_auth; end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:216
  def issue_challenge_response(negotiate); end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:195
  def seal(message); end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:201
  def winrm_decrypt(resp); end
end

# Plain text, insecure, HTTP transport
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:138
class WinRM::HTTP::HttpPlaintext < ::WinRM::HTTP::HttpTransport
  # pkg:gem/winrm#lib/winrm/http/transport.rb:139
  def initialize(endpoint, user, pass, opts); end
end

# A generic HTTP transport that utilized HTTPClient to send messages back and forth.
# This backend will maintain state for every WinRMWebService instance that is instantiated so it
# is possible to use GSSAPI with Keep-Alive.
#
# pkg:gem/winrm#lib/winrm/http/transport.rb:23
class WinRM::HTTP::HttpTransport
  # pkg:gem/winrm#lib/winrm/http/transport.rb:26
  def initialize(endpoint, options); end

  # We'll need this to force basic authentication if desired
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:58
  def basic_auth_only!; end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:24
  def endpoint; end

  # Disable SSL Peer Verification
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:70
  def no_ssl_peer_verification!; end

  # Disable SSPI Auth
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:64
  def no_sspi_auth!; end

  # Sends the SOAP payload to the WinRM service and returns the service's
  # SOAP response. If an error occurrs an appropriate error is raised.
  #
  # @param [String] The XML SOAP message
  # @returns [REXML::Document] The parsed response body
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:40
  def send_request(message); end

  # SSL Peer Fingerprint Verification prior to connecting
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:75
  def ssl_peer_fingerprint_verification!; end

  # compare @ssl_peer_fingerprint to current ssl context
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:102
  def verify_ssl_fingerprint(cert); end

  # Connect without verification to retrieve untrusted ssl context
  #
  # pkg:gem/winrm#lib/winrm/http/transport.rb:88
  def with_untrusted_ssl_connection; end

  protected

  # pkg:gem/winrm#lib/winrm/http/transport.rb:113
  def body(message, length, type = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/http/transport.rb:124
  def log_soap_message(message); end
end

# Factory for creating a HTTP transport that can be used for WinRM SOAP calls.
#
# pkg:gem/winrm#lib/winrm/http/transport_factory.rb:20
class WinRM::HTTP::TransportFactory
  # Creates a new WinRM HTTP transport using the specified connection options.
  # @param connection_opts [ConnectionOpts|Hash] The connection ConnectionOpts.
  # @return [HttpTransport] A transport instance for making WinRM calls.
  #
  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:24
  def create_transport(connection_opts); end

  private

  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:36
  def init_kerberos_transport(opts); end

  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:32
  def init_negotiate_transport(opts); end

  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:40
  def init_plaintext_transport(opts); end

  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:44
  def init_ssl_transport(opts); end

  # pkg:gem/winrm#lib/winrm/http/transport_factory.rb:55
  def validate_transport!(transport); end
end

# Exitcode error
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:26
class WinRM::InvalidExitCode < ::WinRM::WinRMError; end

# Shell creation error
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:23
class WinRM::InvalidShellError < ::WinRM::WinRMError; end

# Shell creation error
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:29
class WinRM::InvalidTransportError < ::WinRM::WinRMError
  # pkg:gem/winrm#lib/winrm/exceptions.rb:32
  def initialize(invalid_transport, valid_transports); end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:30
  def invalid_transport; end
end

# pkg:gem/winrm#lib/winrm.rb:23
WinRM::LOG_LEVELS = T.let(T.unsafe(nil), Array)

# This class holds raw output and has convenience methods to parse.
#
# pkg:gem/winrm#lib/winrm/output.rb:17
class WinRM::Output
  # pkg:gem/winrm#lib/winrm/output.rb:18
  def initialize; end

  # Appends stream data to the output
  #
  # pkg:gem/winrm#lib/winrm/output.rb:54
  def <<(data); end

  # @return [Integer] exitcode returned from command
  #
  # pkg:gem/winrm#lib/winrm/output.rb:23
  def exitcode; end

  # Sets the exitcode
  #
  # pkg:gem/winrm#lib/winrm/output.rb:47
  def exitcode=(code); end

  # @return [String] Aggregated stdout and stderr streams
  #
  # pkg:gem/winrm#lib/winrm/output.rb:26
  def output; end

  # @return [String] stderr stream output
  #
  # pkg:gem/winrm#lib/winrm/output.rb:40
  def stderr; end

  # @return [String] stdout stream output
  #
  # pkg:gem/winrm#lib/winrm/output.rb:33
  def stdout; end
end

# PowerShell Remoting Protcol module
#
# pkg:gem/winrm#lib/winrm/psrp/fragment.rb:18
module WinRM::PSRP; end

# PowerShell Remoting Protocol message fragment.
#
# pkg:gem/winrm#lib/winrm/psrp/fragment.rb:20
class WinRM::PSRP::Fragment
  # Creates a new PSRP message fragment
  # @param message_id [Integer] The id of the fragmented message.
  # @param blob [Array] Array of fragmented bytes.
  # @param fragment_id [Integer] The id of this fragment
  # @param start_fragment [Boolean] If the fragment is the first fragment
  # @param end_fragment [Boolean] If the fragment is the last fragment
  #
  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:27
  def initialize(message_id, blob, fragment_id = T.unsafe(nil), start_fragment = T.unsafe(nil), end_fragment = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:35
  def blob; end

  # Returns the raw PSRP message bytes ready for transfer to Windows inside a
  # WinRM message.
  # @return [Array<Byte>] Unencoded raw byte array of the PSRP message.
  #
  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:40
  def bytes; end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:35
  def end_fragment; end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:35
  def fragment_id; end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:35
  def message_id; end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:35
  def start_fragment; end

  private

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:52
  def end_start_fragment; end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:63
  def int16be(int16); end

  # pkg:gem/winrm#lib/winrm/psrp/fragment.rb:59
  def int64be(int64); end
end

# PowerShell Remoting Protocol base message.
# http://download.microsoft.com/download/9/5/E/95EF66AF-9026-4BB0-A41D-A4F81802D92C/%5BMS-PSRP%5D.pdf
#
# pkg:gem/winrm#lib/winrm/psrp/message.rb:24
class WinRM::PSRP::Message
  include ::WinRM::PSRP::UUID

  # Creates a new PSRP message instance
  # @param runspace_pool_id [String] The UUID of the remote shell/runspace pool.
  # @param pipeline_id [String] The UUID to correlate the command/pipeline response
  # @param type [Integer] The PSRP MessageType. This is most commonly
  # specified in hex, e.g. 0x00010002.
  # @param data [String] The PSRP payload as serialized XML
  # @param destination [Integer] The destination for this message - client or server
  #
  # pkg:gem/winrm#lib/winrm/psrp/message.rb:75
  def initialize(runspace_pool_id, type, data, pipeline_id = T.unsafe(nil), destination = T.unsafe(nil)); end

  # Returns the raw PSRP message bytes ready for transfer to Windows inside a
  # WinRM message.
  # @return [Array<Byte>] Unencoded raw byte array of the PSRP message.
  #
  # pkg:gem/winrm#lib/winrm/psrp/message.rb:96
  def bytes; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:91
  def data; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:91
  def destination; end

  # Parses the raw data to a MessageData class
  # @return [MessageData::Base] MessageData corresponding to this message type
  #
  # pkg:gem/winrm#lib/winrm/psrp/message.rb:109
  def parsed_data; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:91
  def pipeline_id; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:91
  def runspace_pool_id; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:91
  def type; end

  private

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:115
  def byte_order_mark; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:119
  def data_bytes; end

  # pkg:gem/winrm#lib/winrm/psrp/message.rb:123
  def int16le(int16); end
end

# Value of message destination when sent to a client
#
# pkg:gem/winrm#lib/winrm/psrp/message.rb:28
WinRM::PSRP::Message::CLIENT_DESTINATION = T.let(T.unsafe(nil), Integer)

# All known PSRP message types
#
# pkg:gem/winrm#lib/winrm/psrp/message.rb:34
WinRM::PSRP::Message::MESSAGE_TYPES = T.let(T.unsafe(nil), Hash)

# Value of message destination when sent to a server
#
# pkg:gem/winrm#lib/winrm/psrp/message.rb:31
WinRM::PSRP::Message::SERVER_DESTINATION = T.let(T.unsafe(nil), Integer)

# PowerShell Remoting Protocol message data.
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/base.rb:21
module WinRM::PSRP::MessageData
  class << self
    # pkg:gem/winrm#lib/winrm/psrp/message_data.rb:35
    def camelize(underscore); end

    # pkg:gem/winrm#lib/winrm/psrp/message_data.rb:29
    def parse(message); end
  end
end

# base class for message data
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/base.rb:23
class WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/base.rb:24
  def initialize(data); end

  # @return [String] raw message data
  #
  # pkg:gem/winrm#lib/winrm/psrp/message_data/base.rb:29
  def raw; end

  protected

  # pkg:gem/winrm#lib/winrm/psrp/message_data/base.rb:33
  def clixml; end
end

# error record message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:19
class WinRM::PSRP::MessageData::ErrorRecord < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:40
  def doc; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:32
  def error_category_message; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:36
  def error_details_script_stack_trace; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:20
  def exception; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:24
  def fully_qualified_error_id; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:28
  def invocation_info; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:49
  def property_hash(prop_name); end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:44
  def string_prop(prop_name); end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/error_record.rb:59
  def underscore(camel); end
end

# pipeline host call message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_host_call.rb:19
class WinRM::PSRP::MessageData::PipelineHostCall < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_host_call.rb:20
  def method_identifier; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_host_call.rb:24
  def method_parameters; end
end

# Handles decoding a raw powershell output response
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_output.rb:21
class WinRM::PSRP::MessageData::PipelineOutput < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_output.rb:22
  def output; end

  private

  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_output.rb:28
  def extract_out_string(text); end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_output.rb:42
  def remove_bom(text); end
end

# pipeline state message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:19
class WinRM::PSRP::MessageData::PipelineState < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:32
  def exception_as_error_record; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:28
  def pipeline_state; end
end

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:24
WinRM::PSRP::MessageData::PipelineState::COMPLETED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:26
WinRM::PSRP::MessageData::PipelineState::DISCONNECTED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:25
WinRM::PSRP::MessageData::PipelineState::FAILED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:20
WinRM::PSRP::MessageData::PipelineState::NOT_STARTED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:21
WinRM::PSRP::MessageData::PipelineState::RUNNING = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:23
WinRM::PSRP::MessageData::PipelineState::STOPPED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/pipeline_state.rb:22
WinRM::PSRP::MessageData::PipelineState::STOPPING = T.let(T.unsafe(nil), Integer)

# runspace pool host call message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_host_call.rb:19
class WinRM::PSRP::MessageData::RunspacepoolHostCall < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_host_call.rb:20
  def method_identifier; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_host_call.rb:24
  def method_parameters; end
end

# runspace pool state message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:19
class WinRM::PSRP::MessageData::RunspacepoolState < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:31
  def runspace_state; end
end

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:20
WinRM::PSRP::MessageData::RunspacepoolState::BEFORE_OPEN = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:25
WinRM::PSRP::MessageData::RunspacepoolState::BROKEN = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:23
WinRM::PSRP::MessageData::RunspacepoolState::CLOSED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:24
WinRM::PSRP::MessageData::RunspacepoolState::CLOSING = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:28
WinRM::PSRP::MessageData::RunspacepoolState::CONNECTING = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:29
WinRM::PSRP::MessageData::RunspacepoolState::DISCONNECTED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:26
WinRM::PSRP::MessageData::RunspacepoolState::NEGOTIATION_SENT = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:27
WinRM::PSRP::MessageData::RunspacepoolState::NEGOTIATION_SUCCEEDED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:22
WinRM::PSRP::MessageData::RunspacepoolState::OPENED = T.let(T.unsafe(nil), Integer)

# pkg:gem/winrm#lib/winrm/psrp/message_data/runspacepool_state.rb:21
WinRM::PSRP::MessageData::RunspacepoolState::OPENING = T.let(T.unsafe(nil), Integer)

# session capability message type
#
# pkg:gem/winrm#lib/winrm/psrp/message_data/session_capability.rb:19
class WinRM::PSRP::MessageData::SessionCapability < ::WinRM::PSRP::MessageData::Base
  # pkg:gem/winrm#lib/winrm/psrp/message_data/session_capability.rb:20
  def protocol_version; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/session_capability.rb:24
  def ps_version; end

  # pkg:gem/winrm#lib/winrm/psrp/message_data/session_capability.rb:28
  def serialization_version; end
end

# PowerShell Remoting Protocol message fragmenter.
#
# pkg:gem/winrm#lib/winrm/psrp/message_defragmenter.rb:21
class WinRM::PSRP::MessageDefragmenter
  # pkg:gem/winrm#lib/winrm/psrp/message_defragmenter.rb:22
  def initialize; end

  # pkg:gem/winrm#lib/winrm/psrp/message_defragmenter.rb:26
  def defragment(base64_bytes); end

  # pkg:gem/winrm#lib/winrm/psrp/message_defragmenter.rb:41
  def fragment_from(byte_string); end

  # pkg:gem/winrm#lib/winrm/psrp/message_defragmenter.rb:51
  def message_from(byte_string); end
end

# Creates WinRM::PSRP::Message instances for various PSRP messages
#
# pkg:gem/winrm#lib/winrm/psrp/message_factory.rb:21
class WinRM::PSRP::MessageFactory
  class << self
    # Creates a new PSRP message that creates pipline to execute a command.
    # @param runspace_pool_id [String] The UUID of the remote shell/runspace pool.
    # @param pipeline_id [String] The UUID to correlate the command/pipeline
    # response.
    # @param command [String] The command passed to Invoke-Expression.
    #
    # pkg:gem/winrm#lib/winrm/psrp/message_factory.rb:48
    def create_pipeline_message(runspace_pool_id, pipeline_id, command); end

    # Creates a new init runspace pool PSRP message.
    # @param runspace_pool_id [String] The UUID of the remote shell/runspace pool.
    #
    # pkg:gem/winrm#lib/winrm/psrp/message_factory.rb:35
    def init_runspace_pool_message(runspace_pool_id); end

    # Creates a new session capability PSRP message.
    # @param runspace_pool_id [String] The UUID of the remote shell/runspace pool.
    #
    # pkg:gem/winrm#lib/winrm/psrp/message_factory.rb:25
    def session_capability_message(runspace_pool_id); end

    private

    # Renders the specified template with the given context
    # @param template [String] The base filename of the PSRP message template.
    # @param context [Hash] Any options required for rendering the template.
    # @return [String] The rendered XML PSRP message.
    # @api private
    #
    # pkg:gem/winrm#lib/winrm/psrp/message_factory.rb:64
    def render(template, context = T.unsafe(nil)); end
  end
end

# PowerShell Remoting Protocol message fragmenter.
#
# pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:21
class WinRM::PSRP::MessageFragmenter
  # pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:24
  def initialize(max_blob_length = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:32
  def fragment(message); end

  # pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:30
  def max_blob_length; end

  # pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:30
  def max_blob_length=(_arg0); end

  # pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:29
  def message_id; end
end

# pkg:gem/winrm#lib/winrm/psrp/message_fragmenter.rb:22
WinRM::PSRP::MessageFragmenter::DEFAULT_BLOB_LENGTH = T.let(T.unsafe(nil), Integer)

# Handles decoding a raw powershell output response
#
# pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:22
class WinRM::PSRP::PowershellOutputDecoder
  # Decode the raw SOAP output into decoded PSRP message,
  # Removes BOM and replaces encoded line endings
  # @param raw_output [String] The raw encoded output
  # @return [String] The decoded output
  #
  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:28
  def decode(message); end

  protected

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:71
  def decode_error_record(message); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:52
  def decode_host_call(message); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:48
  def decode_pipeline_output(message); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:101
  def render_exception(parsed); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:118
  def render_exception_as_error_record(parsed); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:110
  def render_native_command_error(parsed); end

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:93
  def render_write_error_exception(parsed); end

  private

  # pkg:gem/winrm#lib/winrm/psrp/powershell_output_decoder.rb:128
  def hex_decode(text); end
end

# Class for reading powershell responses in Receive_Response messages
#
# pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:22
class WinRM::PSRP::ReceiveResponseReader < ::WinRM::WSMV::ReceiveResponseReader
  # Creates a new ReceiveResponseReader
  # @param transport [HttpTransport] The WinRM SOAP transport
  # @param logger [Logger] The logger to log diagnostic messages to
  #
  # pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:26
  def initialize(transport, logger); end

  # Reads PSRP messages sent in one or more receive response messages
  # @param wsmv_message [WinRM::WSMV::Base] A wsmv message to send to endpoint
  # @param wait_for_done_state whether to poll for a CommandState of Done
  # @yield [Message] PSRP Message in response
  # @yieldreturn [Array<Message>] All messages in response
  #
  # pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:36
  def read_message(wsmv_message, wait_for_done_state = T.unsafe(nil)); end

  # Reads streams and returns decoded output
  # @param wsmv_message [WinRM::WSMV::Base] A wsmv message to send to endpoint
  # @yieldparam [string] standard out response text
  # @yieldparam [string] standard error response text
  # @yieldreturn [WinRM::Output] The command output
  #
  # pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:57
  def read_output(wsmv_message); end

  private

  # pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:87
  def find_exit_code(message); end

  # pkg:gem/winrm#lib/winrm/psrp/receive_response_reader.rb:74
  def stream_type(message); end
end

# UUID helper methods
#
# pkg:gem/winrm#lib/winrm/psrp/uuid.rb:18
module WinRM::PSRP::UUID
  # Format a UUID into a GUID compatible byte array for Windows
  #
  # https://msdn.microsoft.com/en-us/library/windows/desktop/aa373931(v=vs.85).aspx
  # typedef struct _GUID {
  #   DWORD Data1;
  #   WORD  Data2;
  #   WORD  Data3;
  #   BYTE  Data4[8];
  # } GUID;
  #
  # @param uuid [String] Canonical hex format with hypens.
  # @return [Array<byte>] UUID in a Windows GUID compatible byte array layout.
  #
  # pkg:gem/winrm#lib/winrm/psrp/uuid.rb:31
  def uuid_to_windows_guid_bytes(uuid); end
end

# Handles the raw WinRM HTTP response. Returns the body as an XML doc
# or raises the appropriate WinRM error if the response is an error.
#
# pkg:gem/winrm#lib/winrm/http/response_handler.rb:21
class WinRM::ResponseHandler
  # @param [String] The raw unparsed response body, if any
  # @param [Integer] The HTTP response status code
  #
  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:24
  def initialize(response_body, status_code); end

  # Processes the response from the WinRM service and either returns an XML
  # doc or raises an appropriate error.
  #
  # @returns [REXML::Document] The parsed response body
  #
  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:33
  def parse_to_xml; end

  private

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:58
  def raise_if_auth_error; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:48
  def raise_if_error; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:99
  def raise_if_soap_fault; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:79
  def raise_if_wmi_error; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:62
  def raise_if_wsman_fault; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:123
  def raise_transport_error; end

  # pkg:gem/winrm#lib/winrm/http/response_handler.rb:40
  def response_xml; end
end

# pkg:gem/winrm#lib/winrm/shells/retryable.rb:19
module WinRM::Shells; end

# Base class for remote shell
#
# pkg:gem/winrm#lib/winrm/shells/base.rb:28
class WinRM::Shells::Base
  include ::WinRM::Shells::Retryable

  # Create a new Cmd shell
  # @param connection_opts [ConnectionOpts] The WinRM connection options
  # @param transport [HttpTransport] The WinRM SOAP transport
  # @param logger [Logger] The logger to log diagnostic messages to
  # @param shell_opts [Hash] Options targeted for the created shell
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:46
  def initialize(connection_opts, transport, logger, shell_opts = T.unsafe(nil)); end

  # Closes the shell if one is open
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:85
  def close; end

  # @return [ConnectionOpts] connection options of the shell
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:60
  def connection_opts; end

  # @return [Logger] logger used for diagnostic messages
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:66
  def logger; end

  # Runs the specified command with optional arguments
  # @param command [String] The command or executable to run
  # @param arguments [Array] The optional command arguments
  # @param block [&block] The optional callback for any realtime output
  # @yieldparam [string] standard out response text
  # @yieldparam [string] standard error response text
  # @yieldreturn [WinRM::Output] The command output
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:78
  def run(command, arguments = T.unsafe(nil), &block); end

  # @return [String] shell id of the currently opn shell or nil if shell is closed
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:54
  def shell_id; end

  # @return [Hash] Options targeted for the created shell
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:69
  def shell_opts; end

  # @return [String] uri that SOAP calls use to identify shell type
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:57
  def shell_uri; end

  # @return [WinRM::HTTP::HttpTransport] transport used to talk with endpoint
  #
  # pkg:gem/winrm#lib/winrm/shells/base.rb:63
  def transport; end

  protected

  # pkg:gem/winrm#lib/winrm/shells/base.rb:147
  def command_output_message(shell_id, command_id); end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:139
  def open_shell; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:143
  def out_streams; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:135
  def response_reader; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:131
  def send_command(_command, _arguments); end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:157
  def with_command_shell(command, arguments = T.unsafe(nil)); end

  private

  # pkg:gem/winrm#lib/winrm/shells/base.rb:208
  def add_finalizer; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:181
  def cleanup_command(command_id); end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:198
  def open; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:215
  def remove_finalizer; end

  # pkg:gem/winrm#lib/winrm/shells/base.rb:175
  def reset_on_error(error); end

  class << self
    # Ruby 3.1+ introduced a change where finalizers cannot allocate new threads.
    # This can raise a ThreadError when the WinRM shell cleanup tries to run in a Thread
    # during garbage collection. Previously, the gem used Thread.new in finalizers.
    #
    # Our solution preserves original behavior safely:
    # 1. Attempt cleanup in a new thread (same as before) for normal execution.
    # 2. If a ThreadError occurs specifically due to "can't alloc thread",
    #    defer cleanup to an at_exit block to ensure the shell is closed properly
    #    without crashing the program.
    # 3. Any other ThreadError is re-raised to avoid hiding unexpected issues.
    #
    # pkg:gem/winrm#lib/winrm/shells/base.rb:107
    def finalize(connection_opts, transport, shell_id); end
  end
end

# pkg:gem/winrm#lib/winrm/shells/base.rb:30
WinRM::Shells::Base::ERROR_OPERATION_ABORTED = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/shells/base.rb:33
WinRM::Shells::Base::FAULTS_FOR_RESET = T.let(T.unsafe(nil), Array)

# pkg:gem/winrm#lib/winrm/shells/base.rb:31
WinRM::Shells::Base::SHELL_NOT_FOUND = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/shells/base.rb:29
WinRM::Shells::Base::TOO_MANY_COMMANDS = T.let(T.unsafe(nil), String)

# Proxy to a remote cmd.exe shell
#
# pkg:gem/winrm#lib/winrm/shells/cmd.rb:20
class WinRM::Shells::Cmd < ::WinRM::Shells::Base
  include ::WinRM::WSMV::SOAP

  protected

  # pkg:gem/winrm#lib/winrm/shells/cmd.rb:48
  def open_shell; end

  # pkg:gem/winrm#lib/winrm/shells/cmd.rb:54
  def out_streams; end

  # pkg:gem/winrm#lib/winrm/shells/cmd.rb:44
  def response_reader; end

  # pkg:gem/winrm#lib/winrm/shells/cmd.rb:31
  def send_command(command, arguments); end

  class << self
    # pkg:gem/winrm#lib/winrm/shells/cmd.rb:23
    def close_shell(connection_opts, transport, shell_id); end
  end
end

# Proxy to a remote PowerShell instance
#
# pkg:gem/winrm#lib/winrm/shells/power_shell.rb:28
class WinRM::Shells::Powershell < ::WinRM::Shells::Base
  include ::WinRM::WSMV::SOAP

  # Create a new powershell shell
  # @param connection_opts [ConnectionOpts] The WinRM connection options
  # @param transport [HttpTransport] The WinRM SOAP transport
  # @param logger [Logger] The logger to log diagnostic messages to
  #
  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:46
  def initialize(connection_opts, transport, logger); end

  # calculate the maimum fragment size so that they will be as large as possible yet
  # no greater than the max_envelope_size_kb on the end point. To calculate this
  # threshold, we:
  # - determine the maximum number of bytes accepted on the endpoint
  # - subtract the non-fragment characters in the SOAP envelope
  # - determine the number of bytes that could be base64 encded to the above length
  # - subtract the fragment header bytes (ids, length, etc)
  #
  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:69
  def max_fragment_blob_size; end

  # Runs the specified command
  # @param command [String] The powershell script to run
  # @param block [&block] The optional callback for any realtime output
  # @yield [Message] PSRP Message in response
  # @yieldreturn [Array<Message>] All messages in response
  #
  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:56
  def send_pipeline_command(command, &block); end

  protected

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:114
  def open_shell; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:127
  def out_streams; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:92
  def response_reader; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:96
  def send_command(command, _arguments); end

  private

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:133
  def base64_deflated(inflated_length); end

  # Powershell v2.0 has a protocol version of 2.1
  # which defaults to a 150 MaxEnvelopeSizeKB
  # later versions default to 500
  #
  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:193
  def default_protocol_envelope_size(protocol_version); end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:137
  def empty_pipeline_envelope; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:197
  def fragmenter; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:145
  def max_envelope_size_kb; end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:157
  def open_shell_payload(shell_id); end

  # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:166
  def wait_for_running(shell_id); end

  class << self
    # pkg:gem/winrm#lib/winrm/shells/power_shell.rb:32
    def close_shell(connection_opts, transport, shell_id); end
  end
end

# Shell mixin for retrying an operation
#
# pkg:gem/winrm#lib/winrm/shells/retryable.rb:21
module WinRM::Shells::Retryable
  # Retries the operation a specified number of times with a delay between
  # @param retries [Integer] The number of times to retry
  # @param delay [Integer] The number of seconds to wait between retry attempts
  #
  # pkg:gem/winrm#lib/winrm/shells/retryable.rb:34
  def retryable(retries, delay); end
end

# pkg:gem/winrm#lib/winrm/shells/retryable.rb:22
WinRM::Shells::Retryable::RETRYABLE_EXCEPTIONS = T.let(T.unsafe(nil), Proc)

# Factory for creating concrete shell instances
#
# pkg:gem/winrm#lib/winrm/shells/shell_factory.rb:22
class WinRM::Shells::ShellFactory
  # Creates a new ShellFactory instance
  # @param connection_opts [ConnectionOpts] The WinRM connection options
  # @param transport [HttpTransport] The WinRM SOAP transport for sending messages
  # @param logger [Logger] The logger to log messages to
  #
  # pkg:gem/winrm#lib/winrm/shells/shell_factory.rb:27
  def initialize(connection_opts, transport, logger); end

  # Creates a new shell instance based off the shell_type
  # @param shell_type [Symbol] The shell type :cmd or :powershell
  # @param shell_opts [Hash] Options targeted for the created shell
  # @return The ready to use shell instance
  #
  # pkg:gem/winrm#lib/winrm/shells/shell_factory.rb:37
  def create_shell(shell_type, shell_opts = T.unsafe(nil)); end
end

# The version of the WinRM library
#
# pkg:gem/winrm#lib/winrm/version.rb:4
WinRM::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:17
module WinRM::WSMV; end

# Base class for all WSMV message classes
#
# pkg:gem/winrm#lib/winrm/wsmv/base.rb:24
class WinRM::WSMV::Base
  include ::WinRM::WSMV::SOAP
  include ::WinRM::WSMV::Header

  # Builds the WSMV message XML payload
  #
  # pkg:gem/winrm#lib/winrm/wsmv/base.rb:29
  def build; end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/base.rb:48
  def create_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/base.rb:44
  def create_header; end

  # pkg:gem/winrm#lib/winrm/wsmv/base.rb:52
  def encode_bytes(bytes); end
end

# WSMV message to execute a command inside a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:20
class WinRM::WSMV::CleanupCommand < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:21
  def initialize(session_opts, opts); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:37
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:33
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:52
  def cleanup_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/cleanup_command.rb:45
  def cleanup_header; end
end

# WSMV message to close a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/close_shell.rb:20
class WinRM::WSMV::CloseShell < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/close_shell.rb:21
  def initialize(session_opts, shell_opts); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/close_shell.rb:35
  def create_body(_body); end

  # pkg:gem/winrm#lib/winrm/wsmv/close_shell.rb:31
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/close_shell.rb:41
  def close_header; end
end

# WSMV message to execute a command inside a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/command.rb:20
class WinRM::WSMV::Command < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:23
  def initialize(session_opts, cmd_opts); end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:29
  def build; end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:21
  def command_id; end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:40
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:36
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:70
  def command_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:84
  def command_header_opts; end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:76
  def command_headers; end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:48
  def init_ops(session_opts, cmd_opts); end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:64
  def issue69_unescape_single_quotes(xml); end

  # pkg:gem/winrm#lib/winrm/wsmv/command.rb:58
  def validate_opts(session_opts, cmd_opts); end
end

# WSMV message to get output from a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:20
class WinRM::WSMV::CommandOutput < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:21
  def initialize(session_opts, command_out_opts); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:38
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:34
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:52
  def header_opts; end

  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:64
  def output_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/command_output.rb:44
  def output_header; end
end

# Handles decoding a raw output response
#
# pkg:gem/winrm#lib/winrm/wsmv/command_output_decoder.rb:20
class WinRM::WSMV::CommandOutputDecoder
  # Decode the raw SOAP output into decoded and human consumable text,
  # Decodes and replaces invalid unicode characters.
  # @param raw_output [String] The raw encoded output
  # @return [String] The decoded output
  #
  # pkg:gem/winrm#lib/winrm/wsmv/command_output_decoder.rb:25
  def decode(raw_output); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/command_output_decoder.rb:34
  def decode_raw_output(raw_output); end

  # pkg:gem/winrm#lib/winrm/wsmv/command_output_decoder.rb:38
  def handle_invalid_encoding(decoded_text); end

  # pkg:gem/winrm#lib/winrm/wsmv/command_output_decoder.rb:48
  def remove_bom(decoded_text); end
end

# WSMV keep alive message
#
# pkg:gem/winrm#lib/winrm/wsmv/configuration.rb:20
class WinRM::WSMV::Configuration < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/configuration.rb:21
  def initialize(session_opts); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/configuration.rb:31
  def create_body(_body); end

  # pkg:gem/winrm#lib/winrm/wsmv/configuration.rb:27
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/configuration.rb:37
  def configuration_headers; end
end

# WSMV message to execute a command via psrp
#
# pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:21
class WinRM::WSMV::CreatePipeline < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:24
  def initialize(session_opts, shell_id, command_id, fragment = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def command_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def command_id=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def fragment; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def fragment=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def shell_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:22
  def shell_id=(_arg0); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:37
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:33
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:59
  def arguments; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:45
  def command_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_pipeline.rb:52
  def command_headers; end
end

# WSMV message to create a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:21
class WinRM::WSMV::CreateShell < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:29
  def initialize(session_opts, shell_opts = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def codepage; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def codepage=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def env_vars; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def env_vars=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def i_stream; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def i_stream=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def idle_timeout; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def idle_timeout=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def noprofile; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def noprofile=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def o_stream; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:26
  def o_stream=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def working_directory; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:27
  def working_directory=(_arg0); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:47
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:43
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:91
  def action_create; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:73
  def environment_vars_body; end

  # backwards compat - idle_timeout as an Iso8601Duration string
  #
  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:69
  def format_idle_timeout(timeout); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:102
  def header_opts; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:53
  def opt_or_default(shell_opts, key, default_value = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:57
  def shell_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:84
  def shell_headers; end
end

# utf8 as default codepage
# https://msdn.microsoft.com/en-us/library/dd317756(VS.85).aspx
#
# pkg:gem/winrm#lib/winrm/wsmv/create_shell.rb:24
WinRM::WSMV::CreateShell::UTF8_CODE_PAGE = T.let(T.unsafe(nil), Integer)

# SOAP header utility mixin
#
# pkg:gem/winrm#lib/winrm/wsmv/header.rb:23
module WinRM::WSMV::Header
  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:126
  def action_command; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:114
  def action_delete; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:174
  def action_enumerate; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:186
  def action_enumerate_pull; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:102
  def action_get; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:138
  def action_receive; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:150
  def action_send; end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:162
  def action_signal; end

  # Merge the various header hashes and make sure we carry all of the attributes
  # through instead of overwriting them.
  #
  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:32
  def merge_headers(*headers); end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:86
  def resource_uri_cmd; end

  # Helper methods for SOAP Headers
  #
  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:76
  def resource_uri_shell(shell_uri); end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:90
  def resource_uri_wmi(namespace = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:198
  def selector_shell_id(shell_id); end

  # pkg:gem/winrm#lib/winrm/wsmv/header.rb:42
  def shared_headers(session_opts); end
end

# WSMan URI of the regular Windows cmd shell
#
# pkg:gem/winrm#lib/winrm/wsmv/header.rb:25
WinRM::WSMV::Header::RESOURCE_URI_CMD = T.let(T.unsafe(nil), String)

# WSMan URI for PowerShell
#
# pkg:gem/winrm#lib/winrm/wsmv/header.rb:28
WinRM::WSMV::Header::RESOURCE_URI_POWERSHELL = T.let(T.unsafe(nil), String)

# WSMV message to create a remote shell
#
# pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:20
class WinRM::WSMV::InitRunspacePool < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:23
  def initialize(session_opts, shell_id, payload); end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:21
  def shell_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:21
  def shell_id=(_arg0); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:35
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:31
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:65
  def action_create; end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:76
  def header_opts; end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:44
  def shell_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/init_runspace_pool.rb:58
  def shell_headers; end
end

# Converts seconds to ISO8601 duration format
#
# pkg:gem/winrm#lib/winrm/wsmv/iso8601_duration.rb:21
module WinRM::WSMV::Iso8601Duration
  class << self
    # Convert the number of seconds to an ISO8601 duration format
    # @see http://tools.ietf.org/html/rfc2445#section-4.3.6
    # @param [Integer] seconds The amount of seconds for this duration
    #
    # pkg:gem/winrm#lib/winrm/wsmv/iso8601_duration.rb:25
    def sec_to_dur(seconds); end
  end
end

# WSMV keep alive message
#
# pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:20
class WinRM::WSMV::KeepAlive < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:23
  def initialize(session_opts, shell_id); end

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:21
  def shell_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:21
  def shell_id=(_arg0); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:34
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:30
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:52
  def header_opts; end

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:40
  def keep_alive_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/keep_alive.rb:44
  def keep_alive_headers; end
end

# Class for reading wsmv Receive_Response messages
#
# pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:23
class WinRM::WSMV::ReceiveResponseReader
  include ::WinRM::WSMV::SOAP
  include ::WinRM::WSMV::Header

  # Creates a new ReceiveResponseReader
  # @param transport [HttpTransport] The WinRM SOAP transport
  # @param logger [Logger] The logger to log diagnostic messages to
  #
  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:30
  def initialize(transport, logger); end

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:36
  def logger; end

  # Reads streams and returns decoded output
  # @param wsmv_message [WinRM::WSMV::Base] A wsmv message to send to endpoint
  # @yieldparam [string] standard out response text
  # @yieldparam [string] standard error response text
  # @yieldreturn [WinRM::Output] The command output
  #
  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:43
  def read_output(wsmv_message); end

  # Reads streams sent in one or more receive response messages
  # @param wsmv_message [WinRM::WSMV::Base] A wsmv message to send to endpoint
  # @param wait_for_done_state whether to poll for a CommandState of Done
  # @yieldparam [Hash] Hash representation of stream with type and text
  # @yieldparam [REXML::Document] Complete SOAP envelope returned to wsmv_message
  #
  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:57
  def read_response(wsmv_message, wait_for_done_state = T.unsafe(nil)); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:71
  def with_output; end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:106
  def command_done?(resp_doc, wait_for_done_state); end

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:80
  def handle_stream(stream, output, resp_doc); end

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:117
  def read_streams(response_document); end

  # pkg:gem/winrm#lib/winrm/wsmv/receive_response_reader.rb:92
  def send_get_output_message(message); end
end

# WSMV SOAP namespaces mixin
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:19
module WinRM::WSMV::SOAP
  # http://schemas.microsoft.com/wbem/wsman/1/config
  #
  # pkg:gem/winrm#lib/winrm/wsmv/soap.rb:32
  def namespaces; end
end

# http://www.w3.org/2003/05/soap-envelope
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:21
WinRM::WSMV::SOAP::NS_ADDRESSING = T.let(T.unsafe(nil), String)

# http://schemas.xmlsoap.org/ws/2004/08/addressing
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:22
WinRM::WSMV::SOAP::NS_CIMBINDING = T.let(T.unsafe(nil), String)

# http://schemas.dmtf.org/wbem/wsman/1/cimbinding.xsd
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:23
WinRM::WSMV::SOAP::NS_ENUM = T.let(T.unsafe(nil), String)

# http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:27
WinRM::WSMV::SOAP::NS_SCHEMA_INST = T.let(T.unsafe(nil), String)

# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:20
WinRM::WSMV::SOAP::NS_SOAP_ENV = T.let(T.unsafe(nil), String)

# http://schemas.xmlsoap.org/ws/2004/09/enumeration
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:24
WinRM::WSMV::SOAP::NS_TRANSFER = T.let(T.unsafe(nil), String)

# http://www.w3.org/2001/XMLSchema-instance
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:28
WinRM::WSMV::SOAP::NS_WIN_SHELL = T.let(T.unsafe(nil), String)

# http://schemas.microsoft.com/wbem/wsman/1/wsmanfault
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:30
WinRM::WSMV::SOAP::NS_WSMAN_CONF = T.let(T.unsafe(nil), String)

# http://schemas.xmlsoap.org/ws/2004/09/transfer
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:25
WinRM::WSMV::SOAP::NS_WSMAN_DMTF = T.let(T.unsafe(nil), String)

# http://schemas.microsoft.com/wbem/wsman/1/windows/shell
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:29
WinRM::WSMV::SOAP::NS_WSMAN_FAULT = T.let(T.unsafe(nil), String)

# http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
#
# pkg:gem/winrm#lib/winrm/wsmv/soap.rb:26
WinRM::WSMV::SOAP::NS_WSMAN_MSFT = T.let(T.unsafe(nil), String)

# Subclasses base, sends additional data to WinRM
#
# pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:20
class WinRM::WSMV::SendData < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:23
  def initialize(session_opts, shell_id, command_id, fragment); end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def command_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def command_id=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def fragment; end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def fragment=(_arg0); end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def shell_id; end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:21
  def shell_id=(_arg0); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:36
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:32
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:44
  def command_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/send_data.rb:56
  def command_headers; end
end

# WSMV message to 'pull' rest of enumeration results from Windows via WQL
#
# pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:7
class WinRM::WSMV::WqlPull < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:8
  def initialize(session_opts, namespace, enumeration_context); end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:14
  def process_response(response); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:30
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:26
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:44
  def wql_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_pull.rb:36
  def wql_header; end
end

# WSMV message to query Windows via WQL
#
# pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:21
class WinRM::WSMV::WqlQuery < ::WinRM::WSMV::Base
  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:22
  def initialize(transport, session_opts, wql, namespace = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:29
  def process_response(response, &block); end

  protected

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:59
  def create_body(body); end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:55
  def create_header(header); end

  private

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:65
  def process_items(items, &block); end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:83
  def wql_body; end

  # pkg:gem/winrm#lib/winrm/wsmv/wql_query.rb:79
  def wql_header; end
end

# Authorization Error
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:20
class WinRM::WinRMAuthorizationError < ::WinRM::WinRMError; end

# WinRM base class for errors
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:17
class WinRM::WinRMError < ::StandardError; end

# non-200 response without a SOAP fault
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:80
class WinRM::WinRMHTTPTransportError < ::WinRM::WinRMError
  # pkg:gem/winrm#lib/winrm/exceptions.rb:83
  def initialize(msg, status_code = T.unsafe(nil)); end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:81
  def status_code; end
end

# A Fault returned in the SOAP response. The XML node contains Code, SubCode and Reason
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:54
class WinRM::WinRMSoapFault < ::WinRM::WinRMError
  # pkg:gem/winrm#lib/winrm/exceptions.rb:59
  def initialize(code, subcode, reason); end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:55
  def code; end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:57
  def reason; end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:56
  def subcode; end
end

# A Fault returned in the SOAP response. The XML node is a MSFT_WmiError
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:68
class WinRM::WinRMWMIError < ::WinRM::WinRMError
  # pkg:gem/winrm#lib/winrm/exceptions.rb:72
  def initialize(error, error_code); end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:70
  def error; end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:69
  def error_code; end
end

# A Fault returned in the SOAP response. The XML node is a WSManFault
#
# pkg:gem/winrm#lib/winrm/exceptions.rb:42
class WinRM::WinRMWSManFault < ::WinRM::WinRMError
  # pkg:gem/winrm#lib/winrm/exceptions.rb:46
  def initialize(fault_description, fault_code); end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:43
  def fault_code; end

  # pkg:gem/winrm#lib/winrm/exceptions.rb:44
  def fault_description; end
end
