Metrics/ClassLength:
    Max: 500

Metrics/MethodLength:
  Max: 20

Naming/InclusiveLanguage:
  Enabled: True

# Excluding spec files
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'spec/*'
    - 'vendor/**/*'
    - '.git/**/*'
