Metrics/ClassLength:
    Max: 500

Metrics/MethodLength:
  Max: 20

Naming/InclusiveLanguage:
  Enabled: True

Style/Documentation:
  Enabled: False

# Excluding spec files
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.7
  Exclude:
    - 'spec/*'
    - 'vendor/**/*'
    - '.git/**/*'
