Metrics/ClassLength:
    Max: 500

Metrics/MethodLength:
  Max: 20

# Excluding spec files
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.5p114
  Exclude:
    - 'spec/*'
    - 'vendor/**/*'
    - '.git/**/*'
