Metrics/ClassLength:
    Max: 500

Metrics/MethodLength:
  Max: 20

Naming/InclusiveLanguage:
  Enabled: True

Style/Documentation:
  Enabled: False

# TODO: Fix all predicate methods
# We have a lot of methods that returns True/False
# but name is totally incompatilbe with predicate method name
# For example: soft_abort - definetly not a predicate method but returns True/False
Naming/PredicateMethod:
  Enabled: False

# Excluding spec files
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.7
  Exclude:
    - 'spec/*'
    - 'vendor/**/*'
    - '.git/**/*'
