# frozen_string_literal: true

module AutoHCK
  Bundler.require
  require 'active_support/core_ext/hash/deep_merge'
  require 'active_support/core_ext/string/inflections'
  require 'csv'
  require 'date'
  require 'erb'
  require 'fileutils'
  require 'json'
  require 'nori/parser/rexml'
  require 'optparse'
  require 'pathname'
  require 'shellwords'
  require 'socket'
  require 'tempfile'
  require 'uri'
  require 'yaml'
  require 'zip'
  require_relative 'auxiliary/autoload_extension'
  extend AutoloadExtension
  autoload_relative :AutoHCKError, 'exceptions'
  autoload_relative :AutoHCKInterrupt, 'exceptions'
  autoload_relative :CLI, 'cli'
  autoload_relative :ClientError, 'setupmanagers/exceptions'
  autoload_relative :ClientRunError, 'setupmanagers/exceptions'
  autoload_relative :ConfigManager, 'engines/config_manager/config_manager'
  autoload_relative :CmdRun, 'auxiliary/cmd_run'
  autoload_relative :CmdRunError, 'exceptions'
  autoload_relative :DiffChecker, 'auxiliary/diff_checker'
  autoload_relative :Downloader, 'auxiliary/downloader'
  autoload_relative :Engine, 'engines/engine'
  autoload_relative :EngineError, 'engines/exceptions'
  autoload_relative :ExtraSoftwareBrokenConfig, 'auxiliary/extra_software/exceptions'
  autoload_relative :ExtraSoftwareManager, 'auxiliary/extra_software/manager'
  autoload_relative :ExtraSoftwareMissingConfig, 'auxiliary/extra_software/exceptions'
  autoload_relative :Github, 'auxiliary/github'
  autoload_relative :GithubInitializationError, 'exceptions'
  autoload_relative :HCKClient, 'setupmanagers/hckclient'
  autoload_relative :HCKInstall, 'engines/hckinstall/hckinstall'
  autoload_relative :HCKStudio, 'setupmanagers/hckstudio'
  autoload_relative :HCKTest, 'engines/hcktest/hcktest'
  autoload_relative :Helper, 'helper'
  autoload_relative :InvalidConfigFile, 'exceptions'
  autoload_relative :InvalidEngineTypeError, 'engines/exceptions'
  autoload_relative :InvalidPathError, 'exceptions'
  autoload_relative :MachineError, 'setupmanagers/exceptions'
  autoload_relative :MachinePidNil, 'setupmanagers/exceptions'
  autoload_relative :MachineRunError, 'setupmanagers/exceptions'
  autoload_relative :Models, 'models'
  autoload_relative :MultiLogger, 'auxiliary/multi_logger'
  autoload_relative :NotImplementedError, 'exceptions'
  autoload_relative :OpenJsonError, 'exceptions'
  autoload_relative :Pgroup, 'auxiliary/pgroup'
  autoload_relative :PhysHCK, 'setupmanagers/physhck/physhck'
  autoload_relative :Playlist, 'engines/hcktest/playlist'
  autoload_relative :Project, 'project'
  autoload_relative :QemuHCK, 'setupmanagers/qemuhck/qemuhck'
  autoload_relative :QemuHCKError, 'setupmanagers/qemuhck/exceptions'
  autoload_relative :QemuMachine, 'setupmanagers/qemuhck/qemu_machine'
  autoload_relative :QemuRunError, 'setupmanagers/qemuhck/exceptions'
  autoload_relative :ReplacementMap, 'auxiliary/replacement_map'
  autoload_relative :ResourceScope, 'auxiliary/resource_scope'
  autoload_relative :ResultUploader, 'resultuploaders/result_uploader'
  autoload_relative :SetupManager, 'setupmanagers/setupmanager'
  autoload_relative :SetupManagerError, 'setupmanagers/exceptions'
  autoload_relative :Slirp, 'setupmanagers/qemuhck/slirp'
  autoload_relative :StudioConnectError, 'setupmanagers/exceptions'
  autoload_relative :SysInfoParser, 'auxiliary/sysinfo_parser'
  autoload_relative :Targets, 'engines/hcktest/targets'
  autoload_relative :Tests, 'engines/hcktest/tests'
  autoload_relative :Tools, 'engines/hcktest/tools'
  autoload_relative :Trap, 'trap'
end
