# frozen_string_literal: true

module AutoHCK
  Bundler.require
  require 'active_support/core_ext/hash/deep_merge'
  require 'active_support/core_ext/string/inflections'
  require 'csv'
  require 'date'
  require 'erb'
  require 'fileutils'
  require 'json'
  require 'nori/parser/rexml'
  require 'optparse'
  require 'pathname'
  require 'shellwords'
  require 'socket'
  require 'tempfile'
  require 'uri'
  require 'yaml'
  require 'zip'
  autoload :AutoHCKError, './lib/exceptions'
  autoload :AutoHCKInterrupt, './lib/exceptions'
  autoload :CLI, './lib/cli'
  autoload :ClientError, './lib/setupmanagers/exceptions'
  autoload :ClientRunError, './lib/setupmanagers/exceptions'
  autoload :ConfigManager, './lib/engines/config_manager/config_manager'
  autoload :CmdRun, './lib/auxiliary/cmd_run'
  autoload :CmdRunError, './lib/exceptions'
  autoload :DiffChecker, './lib/auxiliary/diff_checker'
  autoload :Downloader, './lib/auxiliary/downloader'
  autoload :Engine, './lib/engines/engine'
  autoload :EngineError, './lib/engines/exceptions'
  autoload :ExtraSoftwareBrokenConfig, './lib/auxiliary/extra_software/exceptions'
  autoload :ExtraSoftwareManager, './lib/auxiliary/extra_software/manager'
  autoload :ExtraSoftwareMissingConfig, './lib/auxiliary/extra_software/exceptions'
  autoload :Github, './lib/auxiliary/github'
  autoload :GithubInitializationError, './lib/exceptions'
  autoload :HCKClient, './lib/setupmanagers/hckclient'
  autoload :HCKInstall, './lib/engines/hckinstall/hckinstall'
  autoload :HCKStudio, './lib/setupmanagers/hckstudio'
  autoload :HCKTest, './lib/engines/hcktest/hcktest'
  autoload :Helper, './lib/helper'
  autoload :InvalidConfigFile, './lib/exceptions'
  autoload :InvalidEngineTypeError, './lib/engines/exceptions'
  autoload :InvalidPathError, './lib/exceptions'
  autoload :MachineError, './lib/setupmanagers/exceptions'
  autoload :MachinePidNil, './lib/setupmanagers/exceptions'
  autoload :MachineRunError, './lib/setupmanagers/exceptions'
  autoload :Models, './lib/models'
  autoload :MultiLogger, './lib/auxiliary/multi_logger'
  autoload :NotImplementedError, './lib/exceptions'
  autoload :OpenJsonError, './lib/exceptions'
  autoload :Pgroup, './lib/auxiliary/pgroup'
  autoload :PhysHCK, './lib/setupmanagers/physhck/physhck'
  autoload :Playlist, './lib/engines/hcktest/playlist'
  autoload :Project, './lib/project'
  autoload :QemuHCK, './lib/setupmanagers/qemuhck/qemuhck'
  autoload :QemuHCKError, './lib/setupmanagers/qemuhck/exceptions'
  autoload :QemuMachine, './lib/setupmanagers/qemuhck/qemu_machine'
  autoload :QemuRunError, './lib/setupmanagers/qemuhck/exceptions'
  autoload :ReplacementMap, './lib/auxiliary/replacement_map'
  autoload :ResourceScope, './lib/auxiliary/resource_scope'
  autoload :ResultUploader, './lib/resultuploaders/result_uploader'
  autoload :SetupManager, './lib/setupmanagers/setupmanager'
  autoload :SetupManagerError, './lib/setupmanagers/exceptions'
  autoload :Slirp, './lib/setupmanagers/qemuhck/slirp'
  autoload :StudioConnectError, './lib/setupmanagers/exceptions'
  autoload :SysInfoParser, './lib/auxiliary/sysinfo_parser'
  autoload :Targets, './lib/engines/hcktest/targets'
  autoload :Tests, './lib/engines/hcktest/tests'
  autoload :Tools, './lib/engines/hcktest/tools'
  autoload :Trap, './lib/trap'
end
