name: Check

on:
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'ruby' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  rspec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup AutoHCK
      uses: ./.github/actions/setup-autohck
    - name: RSpec run
      run: bundle exec rspec

  typecheck:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup AutoHCK
      uses: ./.github/actions/setup-autohck

    - name: Check for out-of-date RBIs
      run: bundle exec tapioca gems --verify
    - name: Run sorbet type check
      run: bundle exec srb typecheck

  rubocop:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup AutoHCK
      uses: ./.github/actions/setup-autohck

    - name: RuboCop run
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: rubocop.sarif
